### ISSUE TITLE
Cannot install from sdist obtained from PyPI

### ISSUE THREAD

**Issue by awvwgk** [xitorch/xitorch#16]
**Describe the bug**

Installation with pip from sdist fails (version 0.3.0).

**To Reproduce**

Presumably, the directory layout from the git repository is assumed in `setup.py`, but the relevant files are not actually included in the sdist.

```
source tree in: /home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work
export PREFIX=/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export BUILD_PREFIX=/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/_build_env
export SRC_DIR=/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work
Using pip 22.0.4 from $PREFIX/lib/python3.10/site-packages/pip (python 3.10)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-aj1o1cc3
Created temporary directory: /tmp/pip-req-tracker-hqkvtmg0
Initialized build tracking at /tmp/pip-req-tracker-hqkvtmg0
Created build tracker: /tmp/pip-req-tracker-hqkvtmg0
Entered build tracker: /tmp/pip-req-tracker-hqkvtmg0
Created temporary directory: /tmp/pip-install-gylksics
Processing $SRC_DIR
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-hqkvtmg0'
  Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
  Created temporary directory: /tmp/pip-pip-egg-info-uaj5m5_v
  Running command python setup.py egg_info
  Preparing metadata (setup.py): started
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work/setup.py", line 49, in <module>
      install_requires=get_requirements("requirements.txt"),
    File "/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work/setup.py", line 32, in get_requirements
      with open(absdir(fname), "r") as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work/requirements.txt'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-uaj5m5_v
  cwd: /home/conda/staged-recipes/build_artifacts/xitorch_1649528643673/work/
  Preparing metadata (setup.py): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Expected behavior**

Install cleanly from sdist.

**Systems:**
 - OS: Linux, MacOS, Windows
 - Python version: 3.10
 - PyTorch version: 1.11
 - xitorch version: 0.3.0

**Additional context**

See https://github.com/conda-forge/staged-recipes/pull/18636

**Comment by mfkasim1** [comment]
Hi, sorry for the very late response. I'm not familiar with `sdist`, so can you suggest a way to fix this?
