### ISSUE TITLE
Example 2 broken

### ISSUE THREAD

**Issue by jwittke** [xitorch/xitorch#6]
Running the second example 02, I run into following error:

Traceback (most recent call last):
  File "/home/jwittke/py_tmp/main.py", line 125, in <module>
    mainopt()
  File "/home/jwittke/py_tmp/main.py", line 110, in mainopt
    loss, yt = get_loss(pos, vel, ts, pos_target)
  File "/home/jwittke/py_tmp/main.py", line 29, in get_loss
    yt = solve_ivp(dydt, ts, y0, fwd_options={"method": "rk4"})
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/integrate/solve_ivp.py", line 92, in solve_ivp
    return _SolveIVP.apply(pfcn, ts, fwd_options, bck_options, len(params), y0, *params, *pfcn.objparams())
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/integrate/solve_ivp.py", line 114, in forward
    yt = solver(pfcn, ts, y0, params, **config)
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/_impls/integrate/ivp/adaptive_rk.py", line 178, in rk45_adaptive
    return _rk_adaptive(fcn, ts, y0, params, RK45, **kwargs)
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/_impls/integrate/ivp/adaptive_rk.py", line 164, in _rk_adaptive
    return solver.solve()
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/_impls/integrate/ivp/adaptive_rk.py", line 72, in solve
    rk_state = self._step(rk_state, ts[i])
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/_impls/integrate/ivp/adaptive_rk.py", line 83, in _step
    rk_state, t1_achieved = self._single_step(rk_state, t1)
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/_impls/integrate/ivp/adaptive_rk.py", line 98, in _single_step
    ynew, fnew = rk_step(self.func, t0, y0, f0, hstep, abck)
  File "/home/jwittke/anaconda3/lib/python3.7/site-packages/xitorch/_impls/integrate/ivp/adaptive_rk.py", line 16, in rk_step
    K[s] = func(t + c * h, y + dy)
RuntimeError: The size of tensor a (2) must match the size of tensor b (128) at non-singleton dimension 3

I am using:

conda version : 4.9.2
conda-build version : 3.18.11
python version : 3.7.6.final.0
platform : linux-64
user-agent : conda/4.9.2 requests/2.23.0 CPython/3.7.6 Linux/4.4.0-194-generic ubuntu/16.04.7 glibc/2.23

pytorch   1.7.1   py3.7_cpu_0  [cpuonly]  pytorch

**Comment by mfkasim1** [comment]
Hi @jwittke 

Thank you for reporting the bug.
I have found the problem and will commit the fix soon.
`solve_ivp` is the function I rarely use, so I'd be very happy if you can use it and report if there's any issue with it (or even more if you could contribute to it).
